### PR TITLE
extract_pandas_traintime_categories: return empty list if pandas_categorical is null in model file

### PR DESCRIPTION
**Pull request by chenglin**
In lightgbm model file, pandas_categorical may be null. 
When call data_processing._dataframe_to_ndarray, exception happend caused by `if len(cat_cols) != len(pd_traintime_categories)`
TypeError: object of type 'NoneType' has no len()

### CODE REVIEW

**Comment by siboehm** [comment]
Thanks for the PR! I'll look through this & make a new release Sunday at the latest.

**Comment by siboehm** [comment]
It looks good, but I'd like to add a test for it, and fix the one failing test. Can you allow me to push to your PR? There should be a box to tick for you called `Allow edits from maintainers`.

**Comment by chenglin** [comment]
> It looks good, but I'd like to add a test for it, and fix the one failing test. Can you allow me to push to your PR? There should be a box to tick for you called `Allow edits from maintainers`.

done

**Comment by siboehm** [comment]
Tests were passing, thanks @chenglin for the PR!

**Pull request merged**
